name: Daily Auto Commit

on:
  schedule:
    - cron: "0 15 * * *" # 毎日 JST 0:00 頃
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "memo-bot"
          git config user.email "memo-bot@example.com"

      - name: Pull latest changes
        run: git pull --rebase

      - name: Commit and push if needed
        run: |
          if git status --porcelain | grep .; then
            git add -A
            git commit -m "Auto update $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi
